# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\data\test code\python\qt\lcd_debug\UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1387, 865)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.screen_index = QtWidgets.QComboBox(self.centralwidget)
        self.screen_index.setGeometry(QtCore.QRect(150, 70, 87, 22))
        self.screen_index.setCurrentText("")
        self.screen_index.setObjectName("screen_index")
        self.fps_list = QtWidgets.QComboBox(self.centralwidget)
        self.fps_list.setGeometry(QtCore.QRect(150, 120, 87, 22))
        self.fps_list.setObjectName("fps_list")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 70, 81, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 110, 81, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 150, 81, 31))
        self.label_3.setObjectName("label_3")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(150, 160, 87, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.r_code = QtWidgets.QTextEdit(self.centralwidget)
        self.r_code.setGeometry(QtCore.QRect(60, 230, 601, 192))
        self.r_code.setObjectName("r_code")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(720, 270, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.replace_code = QtWidgets.QPushButton(self.centralwidget)
        self.replace_code.setGeometry(QtCore.QRect(720, 340, 93, 28))
        self.replace_code.setObjectName("replace_code")
        self.debug_window = QtWidgets.QTextBrowser(self.centralwidget)
        self.debug_window.setGeometry(QtCore.QRect(60, 470, 601, 341))
        self.debug_window.setObjectName("debug_window")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 190, 121, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 430, 121, 31))
        self.label_5.setObjectName("label_5")
        self.hs_mode = QtWidgets.QCheckBox(self.centralwidget)
        self.hs_mode.setGeometry(QtCore.QRect(280, 160, 91, 19))
        self.hs_mode.setObjectName("hs_mode")
        self.code_pack = QtWidgets.QCheckBox(self.centralwidget)
        self.code_pack.setGeometry(QtCore.QRect(390, 160, 91, 19))
        self.code_pack.setObjectName("code_pack")
        self.sync_te = QtWidgets.QCheckBox(self.centralwidget)
        self.sync_te.setEnabled(False)
        self.sync_te.setGeometry(QtCore.QRect(480, 160, 91, 19))
        self.sync_te.setInputMethodHints(QtCore.Qt.ImhNone)
        self.sync_te.setCheckable(True)
        self.sync_te.setObjectName("sync_te")
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(280, 120, 101, 19))
        self.checkBox_4.setObjectName("checkBox_4")
        self.adb_devices_Info = QtWidgets.QComboBox(self.centralwidget)
        self.adb_devices_Info.setGeometry(QtCore.QRect(150, 20, 87, 22))
        self.adb_devices_Info.setCurrentText("")
        self.adb_devices_Info.setObjectName("adb_devices_Info")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(60, 20, 81, 31))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1387, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "屏幕"))
        self.label_2.setText(_translate("MainWindow", "帧率"))
        self.label_3.setText(_translate("MainWindow", "cmd type"))
        self.r_code.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "获取code"))
        self.replace_code.setText(_translate("MainWindow", "替换code"))
        self.label_4.setText(_translate("MainWindow", "在这里替换code："))
        self.label_5.setText(_translate("MainWindow", "DEBUG窗口："))
        self.hs_mode.setText(_translate("MainWindow", "hs_mode"))
        self.code_pack.setText(_translate("MainWindow", "打包"))
        self.sync_te.setText(_translate("MainWindow", "sycn TE"))
        self.checkBox_4.setText(_translate("MainWindow", "全帧率替换"))
        self.label_6.setText(_translate("MainWindow", "手机"))
